vich_uploader:
    db_driver: orm
    mappings:
        spot_image:
            uri_prefix: /images/spots
            upload_destination: '%kernel.project_dir%/public/image/spots'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
