version: '3'
services:
  php:
    container_name: seekriders_backend
    build:
      context: ./
    environment:
      - APP_ENV=dev
      - APP_SECRET=4eptYX56PvT3SXbMtSvLjHxL5crg2Bnw
    volumes:
      - ./:/var/www
  nginx:
    container_name: seekriders_nginx
    build:
      context: ./nginx
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
  mysql:
    container_name: seekriders_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  phpmyadmin:
    image: phpmyadmin
    container_name: seekriders_phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      PMA_HOST: mysql
#  frontend:
#    command: bash -c 'npm i && npm run dev'
#    container_name: seekriders_frontend
#    build:
#      context: ./frontend
#    expose:
#      - '3000'
#    image: node
#    ports:
#      - '3000:3000'
#    user: node
#    volumes:
#      - ../frontend:/home/node/app
#    working_dir: /home/node/app
