version: '3'
services:
  php:
    container_name: seekriders_backend
    build:
      context: ./
    environment:
      - APP_ENV=dev
      - APP_SECRET=4eptYX56PvT3SXbMtSvLjHxL5crg2Bnw
    volumes:
      - ./:/var/www
  nginx:
    container_name: seekriders_nginx
    build:
      context: ./nginx
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log
    depends_on:
      - php
      - mysql
    ports:
      - "80:80"
  mysql:
    container_name: seekriders_mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  node:
    image: node:16-alpine3.12
    volumes:
      - .:/var/www
    ports:
      - "8080:8080"
    working_dir: /var/www
    command: ["yarn"]
volumes:
  dbdata:
